version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
  mongodb:
    image: "mongo"
    environment:
      ATLAS_URI: mongodb+srv://vonypet:hetC55yOwwjI7ySR@cluster0.ljfkg0l.mongodb.net/family?retryWrites=true&w=majority
    volumes:
      - db-data:/foo

volumes:
  db-data:
